# Generated by Django 5.2.7 on 2025-11-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_can_write_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='can_Write',
            new_name='can_write',
        ),
    ]
