# Generated by Django 5.1.2 on 2025-12-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_can_speak_with_sign_language_customuser_can_speak_with_sign_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.IntegerField(choices=[(0, 'Help Waiting'), (1, 'In Help Trip'), (2, 'Finished Helped')], default=0),
        ),
    ]
