# Generated by Django 5.1.2 on 2026-01-09 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_city_post_location_post_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='assistant',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'assistant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='can_speak_with_sign_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='can_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('assistant', 'assistant'), ('blind', 'blind'), ('deaf', 'deaf'), ('volunteer', 'volunteer')], default='volunteer', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.city'),
        ),
    ]
