# Generated by Django 5.1.2 on 2026-01-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_post_location_customuser_assistant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='curent_location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='in_home',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.IntegerField(choices=[(0, 'Help Waiting'), (1, 'In Help Trip'), (2, 'Finished Helped'), (3, 'Cancled')], default=0),
        ),
    ]
