# Generated by Django 5.1.2 on 2026-01-20 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_curent_location_customuser_in_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='help_requesters',
            field=models.ManyToManyField(blank=True, related_name='requested_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helped_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.IntegerField(choices=[(0, 'Help Waiting'), (1, 'In Help Trip'), (2, 'Finished Helped'), (3, 'Canceled')], default=0),
        ),
    ]
