# Generated by Django 5.1.2 on 2026-01-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_device_token_post_help_requesters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='curent_location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
