# Generated by Django 5.1.2 on 2026-01-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.IntegerField(choices=[(0, 'Help Waiting'), (1, 'In Help Trip'), (2, 'Completed'), (3, 'Pinding Approval'), (4, 'In Progress'), (5, 'Canceled')], default=0),
        ),
    ]
